version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: threads-db
    environment:
      POSTGRES_USER: posgres
      POSTGRES_PASSWORD: thread
      POSTGRES_DB: thread
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
